#!/usr/bin/env bash
# Start a long job on the GPU box, detached, and come back to it later.
#
#   ./infra/run.sh pilot 'uv run python -m sqlrl.training.grpo_spider --pilot'
#   ./infra/run.sh --status              what is running, and how did the last runs end
#   ./infra/run.sh --status pilot        one job
#   ./infra/run.sh --log pilot           last 50 lines
#   ./infra/run.sh --follow pilot        stream it
#
# Every ad-hoc `ssh ... nohup python ...` in this project has failed the same
# three ways, so this exists to make them impossible:
#
# 1. **`uv: command not found`, reported as success.** A non-interactive ssh
#    command is not a login shell, so /etc/profile.d never runs and uv (which
#    lives in ~/.local/bin) is not on PATH. The old sweep script died on this
#    instantly, printed nothing useful, and exited 0. PATH is set explicitly
#    below and the preflight refuses to start without uv.
# 2. **Logs in /tmp.** Wiped on the reboot that an idle-shutdown causes, which
#    is exactly when you want to read them. Logs go to the repo's logs/.
# 3. **No way to tell "still running" from "finished" from "died".** A status
#    file is written before the job starts and overwritten with the exit code
#    when it ends, so --status can always answer.
# 4. **Secrets in .env that a non-login shell never loads.** Same root cause as
#    (1), and it has bitten this project separately for SQL_LLM_BUCKET (an S3
#    sync that silently uploaded nothing) and for WANDB_API_KEY. The wrapper
#    sources .env, and the preflight refuses to start a job that asked for W&B
#    logging without a key -- losing the metrics of a two-hour run because a
#    variable was unset is not a mistake worth making twice.
#
# The job is detached with setsid, so it survives losing the SSH connection --
# a dropped laptop lid should not kill a training run.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH="$HERE/ssh.sh"
REPO=/opt/sql-llm/repo
LOGS="$REPO/logs"

usage() { sed -n '2,8p' "$0"; }

MODE=start
NAME=""
CMD=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --status) MODE=status; shift ;;
        --log)    MODE=log; shift ;;
        --follow) MODE=follow; shift ;;
        -h|--help) usage; exit 0 ;;
        *)
            if [[ -z "$NAME" ]]; then NAME="$1"; else CMD="$1"; fi
            shift
            ;;
    esac
done

case "$MODE" in
    status)
        if [[ -n "$NAME" ]]; then
            "$SSH" "cat logs/$NAME.status 2>/dev/null || echo 'no such job: $NAME'"
        else
            "$SSH" 'for f in logs/*.status; do
                     [ -e "$f" ] || continue
                     printf "%-24s %s\n" "$(basename "$f" .status)" "$(cat "$f")"
                   done'
        fi
        exit 0
        ;;
    log)
        [[ -n "$NAME" ]] || { echo "need a job name" >&2; exit 1; }
        "$SSH" "tail -n 50 logs/$NAME.log"
        exit 0
        ;;
    follow)
        [[ -n "$NAME" ]] || { echo "need a job name" >&2; exit 1; }
        "$SSH" "tail -f -n 50 logs/$NAME.log"
        exit 0
        ;;
esac

[[ -n "$NAME" && -n "$CMD" ]] || { usage; exit 1; }

STAMP=$(date -u +%Y%m%dT%H%M%SZ)

# Whether the job wants W&B is decided here, on the client, so that $CMD is
# never interpolated into shell syntax on the box -- see the .cmd file below.
NEEDS_WANDB=1
case "$CMD" in *"report-to none"*|*"report_to=none"*|*--inspect*) NEEDS_WANDB=0 ;; esac

# The command goes to its own file, piped as raw text so nothing in it is ever
# parsed as shell by the generator. Interpolating a training command into a
# generated script breaks the moment the command contains a quote -- which it
# did, on the first try.
printf '%s\n' "$CMD" | "$SSH" "mkdir -p logs && cat > logs/$NAME.cmd"

# Written to the box as a file rather than inlined into the ssh command line:
# nesting three levels of quoting around a training command is how you end up
# debugging your shell instead of your model.
"$SSH" "mkdir -p logs && cat > logs/$NAME.sh" <<REMOTE
#!/usr/bin/env bash
# Generated by infra/run.sh at $STAMP. Overwritten on the next run of "$NAME".
set -uo pipefail

# The whole reason this file exists -- see the header of infra/run.sh.
export PATH="\$HOME/.local/bin:\$PATH"
cd "$REPO"

# Secrets live here, not in the environment: a non-login shell loads neither
# /etc/profile.d nor ~/.bashrc, so anything set there is invisible to us.
if [ -f .env ]; then
    set -a; . ./.env; set +a
fi

fail() { echo "PREFLIGHT FAIL: \$1"; echo "preflight: \$1" > "$LOGS/$NAME.status"; exit 127; }
command -v uv >/dev/null 2>&1 || fail "uv not on PATH"
nvidia-smi >/dev/null 2>&1     || fail "no GPU visible"
[ -d data/processed ]          || fail "data/processed missing"
# Checked before the run rather than discovered after it: a job that logs to
# W&B without a key either dies at import or, worse, trains fine and throws the
# curves away.
[ "$NEEDS_WANDB" -eq 0 ] || [ -n "\${WANDB_API_KEY:-}" ] || fail "WANDB_API_KEY unset (not in .env?)"

echo "=== $NAME @ $STAMP ==="
echo "commit: \$(git log --oneline -1)"
echo "gpu:    \$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader)"
echo "cmd:    \$(cat "$LOGS/$NAME.cmd")"
echo

bash "$LOGS/$NAME.cmd"
code=\$?

echo
echo "=== exit \$code ==="
if [ \$code -eq 0 ]; then
    echo "ok (finished \$(date -u +%Y-%m-%dT%H:%M:%SZ))" > "$LOGS/$NAME.status"
else
    # Loud, and specific. A run that failed must never read as one that worked.
    echo "FAILED exit \$code (at \$(date -u +%Y-%m-%dT%H:%M:%SZ))" > "$LOGS/$NAME.status"
fi
REMOTE

# A wrapper with a syntax error dies before it can write its own status, so the
# job would sit at "running" forever. Parse it first; that failure mode already
# happened once.
"$SSH" "bash -n logs/$NAME.sh" || {
    echo "generated wrapper does not parse -- not launching" >&2
    exit 1
}

"$SSH" "chmod +x logs/$NAME.sh &&
        echo 'running (started $STAMP)' > logs/$NAME.status &&
        setsid nohup bash logs/$NAME.sh > logs/$NAME.log 2>&1 < /dev/null &
        sleep 1; echo started"

cat <<EOF

  job    : $NAME
  log    : $REPO/logs/$NAME.log
  status : ./infra/run.sh --status $NAME
  follow : ./infra/run.sh --follow $NAME
EOF
